### PR TITLE
update lesscss compiler to 1.3.3

### PR DESCRIPTION
**Pull request by trumbitta**
This is needed for some new LESS syntax

### CODE REVIEW

**Comment by trumbitta** [comment]
@candrews: @marceloverdijk redirected me to you :smile_cat: 
do you have plans about a new release on Maven Central any time soon?

The project I work on would really benefit from this upgrade to LESS 1.3.1

**Comment by uzikilon** [comment]
+1

1.3.3 is the latest on http://lesscss.org

**Comment by trumbitta** [comment]
@uzikilon having 1.3.3 would be great, but given that the java lesscss compiler is now available on Maven Central at v1.3.1, I thought 1.3.1 would've been easier to obtain :dart:

**Comment by uzikilon** [comment]
@trumbitta I am no maven expert, but http://search.maven.org/#artifactdetails%7Corg.webjars%7Cless%7C1.3.3%7Cjar

**Comment by trumbitta** [comment]
@uzikilon I think these are the official ones :) http://search.maven.org/#search%7Cga%7C1%7Corg.lesscss

update: btw I'll look into the one you pointed, because I need to get my own problem sorted out before March 5th :fearful:

**Comment by uzikilon** [comment]
@trumbitta I see. seems like this project is no longer being maintained anyway.

**Comment by buurd** [comment]
@trumbitta @uzikilon You should look at https://github.com/marceloverdijk/lesscss-java/pull/17 and build both this and that project yourself if you are in a hurry. I did, not sure if I pushed the latest changes we did.

**Comment by trumbitta** [comment]
@buurd thank you for your hint, unfortunately I can't use self-built artifacts which are not on Maven Central for my project :-/

**Comment by cpopov** [comment]
We will bump it up lesscss 1.3.3

**Comment by trumbitta** [comment]
@cpopov great news :+1: any vague ETA?

**Comment by cpopov** [comment]
It could be done ASAP, but I'd like to review any outstanding defects.

**Comment by cpopov** [comment]
fixed, it will be in release 1.3.3

**Pull request closed without merging**
