### PR TITLE
Add option to compile less files under Node.js

### PR DESCRIPTION
**Pull request by trask**
Node.js is much much faster than Rhino.

A similar option was added to requirejs-maven-plugin recently.

### CODE REVIEW

**Comment by cpopov** [comment]
Good idea

**Comment by cpopov** [comment]
Auto-merged. I hope it works fine. Are you interested in becoming a committer? Talk to Marcel (the owner)

**Comment by cpopov** [comment]
Hi, why didn't you use the official production lesscss.js file?

**Comment by trask** [comment]
I think the production lesscss.js file had browser dependencies and didn't run under node, so I looked at how npm lessc worked instead, and it used the uncompiled less js (and didn't link in the browser related code).  I've since switched to Grunt, which unfortunately means now I have 2 build steps (Grunt and Maven), but has advantages as well.

**Comment by dynisor** [comment]
cpopov Can we get this pushed into Maven Central? Maybe update it to 1.3.4 or 1.4.0?

**Comment by koraysels** [comment]
yes please put it in central and update :smile:

**Comment by mudlee** [comment]
Yes please, push into the Maven Central!

**Comment by koraysels** [comment]
I found a great alternative, https://github.com/allegro/grunt-maven-plugin , works perfectly

**Comment by mudlee** [comment]
Well, sound great, but:
- it seems to be a little bit complex to me
- I have some bad experiences with the company allegro... :>

Anyway, thank you!

**Pull request merged**
