### PR TITLE
Adding outputFileFormat parameter, Updating documentation

### PR DESCRIPTION
**Pull request by pfgray**

### CODE REVIEW

**Comment by sandroboehme** [comment]
Thats a nice addition. Can you write a little test case for that so that it doesn't get broken from other commits over time?

**Comment by pfgray** [comment]
Yup, let me know if that's good!

**Comment by sandroboehme** [comment]
Wouldn't that #16 already solve your problem?

**Comment by sandroboehme** [comment]
It is released already from here: https://github.com/sandroboehme/lesscss-maven-plugin

**Comment by pfgray** [comment]
Yes, although outputFileFormat will allow for file prefixes as well.

**Comment by sandroboehme** [comment]
Thats a good point Paul. When looking at #16 I like the integration tests a lot and your implementation allows for file prefixes. This means I need to merge it. I can do that but as I don't have too much free time right now it will take some time.

**Pull request merged**
