### PR TITLE
Watch mode for the lesscss Maven plugin

### PR DESCRIPTION
**Pull request by sandroboehme**
Hello Marcel,

respect for your work on the lesscss Maven plugin. It is solid work.
For my project I need a watch feature so I implemented one on a fork of your plugin.
I would be happy if you merge it back in your repo. What do you think? Please tell me if there are any questions about my code.

Best,

Sandro

### CODE REVIEW

**Comment by tjerkw** [comment]
This would be really useful to add.

**Comment by gilday** [comment]
+1

**Comment by just-boris** [comment]
+1
@marceloverdijk, please pay attention to it

**Comment by dmitrif** [comment]
+1

**Comment by sandroboehme** [comment]
@chubbard please tell me if you see any problem with the implementation provided. I'm open to finding solutions for them.

**Comment by sandroboehme** [comment]
@chubbard 
I merged the new feature with the latest upstream. A test for the watch feature is also included.

The change basically works like that: I extracted the compilation of the source files to compileIfChanged() to be able to call it in the watch mode and in the non watch mode. In the watch mode the thread will continuously call compileIfChanged() and then sleep in the specified watch interval. Forcing a compilation will be disabled in this mode.

Please tell me if there is something I can do to get that accepted and committed here.

**Comment by tlei123** [comment]
Hi ALL!

Has @marceloverdijk elected a successor Project Lead for this LessCSS Maven Plugin Project?  I understand he's moving on to other things, but I haven't heard any news about Lead succession.

I'd also like to Contribute but don't know who else besides Marcel to contact.

Thx in advance for any answers/updates!

Tze

**Comment by sandroboehme** [comment]
Fixed in 1.7.0.1.0.

**Pull request closed without merging**
